@echo off
echo Aggressively cleaning project...

echo Removing node_modules...
rd /s /q "node_modules" 2>nul

echo Removing .expo directory...
rd /s /q ".expo" 2>nul

echo Removing package-lock.json...
del package-lock.json 2>nul

echo Clearing npm cache...
npm cache clean --force 2>nul

echo Reinstalling dependencies...
npm install

echo Starting Expo with clear cache...
cd /d "%~dp0"
npx expo start --web --port 8095 --clear 